---
- hosts: "prod-australia"
#  any_errors_fatal: true
  user: root
#  vars:
#    wlshome: /app/weblogic/vodafone/prod
#    jdkhome: /app/jdk/prod
  
  tasks:

    - include_vars: "{{ playbook_dir }}/myenv_{{ myenv }}.yml"

    - block:

      - debug: 
          msg: " WebLogic Home is: {{ wlshome }}"

      - debug:
          msg: " JDK Home is: {{ jdkhome }}"

      run_once: true

- hosts: "nonprod-australia"
  user: root

  tasks:


    - block:

      - debug:
          msg: " WebLogic Home is: {{ hostvars[groups['prod-australia'][0]]['wlshome'] }}"

      - debug:
          msg: " JDK Home is: {{  hostvars[groups['prod-australia'][0]]['wlshome'] }}"

      run_once: true

    - set_fact:
        myserviceuser: wlsadmin

    - debug:
        msg: "User is {{ myserviceuser }}"
      run_once: true

    
